@baseUrl = http://localhost:5000

@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "postId" : "64745c9660c7315a1c231624",
  "type" : "like",
  "userTo": "646e08ba753161ea9ae8b59a",
  "previousReaction" : "",
  "postReactions" : {"like": 1,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0},
  "profilePicture" : ""
}

###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/645b4c0fff825ced1b3f4345/wow/{"like": 0,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/645b4c0fff825ced1b3f4345
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/645b4c0fff825ced1b3f4345/Ronin
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/Ronin
Content-Type: application/json
Accept: application/json
withCredentials: true



